name: Build Multi-Platform

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64
          - os: windows
            arch: amd64
            goos: windows
            goarch: amd64
          - os: darwin
            arch: amd64
            goos: darwin
            goarch: amd64
          - os: darwin
            arch: arm64
            goos: darwin
            goarch: arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Get version
      id: version
      run: |
        # Use the application itself to get the version
        go build -o version-temp .
        VERSION=$(./version-temp)
        rm version-temp
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          go build -ldflags="-s -w" -o version-generator.exe .
        else
          go build -ldflags="-s -w" -o version-generator .
        fi

    - name: Package binary
      run: |
        VERSION=${{ steps.version.outputs.version }}
        PACKAGE_NAME="version-generator-${VERSION}-${{ matrix.os }}-${{ matrix.arch }}"
        mkdir -p "$PACKAGE_NAME"
        
        if [ "${{ matrix.goos }}" = "windows" ]; then
          mv version-generator.exe "$PACKAGE_NAME/"
          zip -r "${PACKAGE_NAME}.zip" "$PACKAGE_NAME"
          echo "package_file=${PACKAGE_NAME}.zip" >> $GITHUB_ENV
        else
          mv version-generator "$PACKAGE_NAME/"
          tar -czf "${PACKAGE_NAME}.tar.gz" "$PACKAGE_NAME"
          echo "package_file=${PACKAGE_NAME}.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: version-generator-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ env.package_file }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/*/*.zip
          artifacts/*/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
